// Command generator builds sing-box rule sets from upstream sources defined in
// sources.yaml. The pipeline is fetch -> parse -> override -> optimize ->
// compile (json + in-process srs). Sources are built concurrently; a failed
// source is reported but never aborts the others.
package main

import (
	"context"
	"flag"
	"fmt"
	"log"
	"os"
	"path/filepath"
	"sort"
	"strconv"
	"strings"

	"golang.org/x/sync/errgroup"

	"github.com/lazyaix-cto/sing-box-geosite/internal/asn"
	"github.com/lazyaix-cto/sing-box-geosite/internal/compile"
	"github.com/lazyaix-cto/sing-box-geosite/internal/config"
	"github.com/lazyaix-cto/sing-box-geosite/internal/model"
	"github.com/lazyaix-cto/sing-box-geosite/internal/override"
	"github.com/lazyaix-cto/sing-box-geosite/internal/parser"
	"github.com/lazyaix-cto/sing-box-geosite/internal/source"
	"github.com/lazyaix-cto/sing-box-geosite/internal/transform"
)

type options struct {
	outDir       string
	overridesDir string
	srsVersions  string
	baseURL      string
	optimize     bool
	resolveASN   bool
}

func main() {
	var (
		configPath  string
		opt         options
		concurrency int
	)
	flag.StringVar(&configPath, "config", "rules/sources.yaml", "path to sources config")
	flag.StringVar(&opt.outDir, "out", "rule", "output directory")
	flag.StringVar(&opt.overridesDir, "overrides", "rules/overrides", "per-category override directory")
	flag.StringVar(&opt.srsVersions, "srs-versions", "auto",
		"srs binary format versions: 'auto' (min required) or a comma list like '1,2,3'")
	flag.StringVar(&opt.baseURL, "base-url", "", "base URL for rule-set links in the generated index (rule/README.md)")
	flag.BoolVar(&opt.optimize, "optimize", true, "apply dedup/collapse/cidr-merge passes")
	flag.BoolVar(&opt.resolveASN, "resolve-asn", false, "expand IP-ASN rules to CIDRs via the ipverse/asn-ip dataset")
	flag.IntVar(&concurrency, "concurrency", 8, "max concurrent sources")
	flag.Parse()

	if err := run(configPath, opt, concurrency); err != nil {
		log.Fatalf("fatal: %v", err)
	}
}

type outcome struct {
	category string
	count    int
	err      error
}

func run(configPath string, opt options, concurrency int) error {
	cfg, err := config.Load(configPath)
	if err != nil {
		return fmt.Errorf("load config: %w", err)
	}
	if err := os.MkdirAll(opt.outDir, 0o755); err != nil {
		return err
	}

	ctx := context.Background()
	outcomes := make([]outcome, len(cfg.Sources))

	var resolver *asn.Resolver
	if opt.resolveASN {
		resolver = asn.NewResolver()
	}

	var g errgroup.Group
	if concurrency > 0 {
		g.SetLimit(concurrency)
	}
	for i, src := range cfg.Sources {
		g.Go(func() error {
			count, err := build(ctx, src, opt, resolver)
			// Capture per-source; return nil so one failure never cancels siblings.
			outcomes[i] = outcome{src.Category, count, err}
			return nil
		})
	}
	_ = g.Wait()

	var failures, total int
	for _, o := range outcomes {
		if o.err != nil {
			log.Printf("[FAIL] %-12s %v", o.category, o.err)
			failures++
			continue
		}
		total += o.count
	}
	log.Printf("done: %d/%d sources ok, %d entries total -> %s",
		len(cfg.Sources)-failures, len(cfg.Sources), total, opt.outDir)

	if err := writeIndex(opt.outDir, opt.baseURL, outcomes); err != nil {
		log.Printf("[warn] write index: %v", err)
	}

	if failures > 0 {
		return fmt.Errorf("%d source(s) failed", failures)
	}
	return nil
}

// writeIndex emits rule/README.md — a table of categories, entry counts and
// links that GitHub renders when browsing the directory.
func writeIndex(outDir, baseURL string, outcomes []outcome) error {
	type row struct {
		cat   string
		count int
	}
	var rows []row
	total := 0
	for _, o := range outcomes {
		if o.err != nil {
			continue
		}
		rows = append(rows, row{o.category, o.count})
		total += o.count
	}
	sort.Slice(rows, func(i, j int) bool { return rows[i].cat < rows[j].cat })

	var b strings.Builder
	b.WriteString("# Rule Sets\n\n")
	b.WriteString("Auto-generated by the sing-box-geosite generator — do not edit by hand.\n\n")
	fmt.Fprintf(&b, "**%d** categories · **%d** entries total.\n\n", len(rows), total)
	if baseURL != "" {
		b.WriteString("Reference in sing-box (`\"format\": \"binary\"`):\n\n")
		fmt.Fprintf(&b, "```\n%s/<Category>.srs\n```\n\n", strings.TrimRight(baseURL, "/"))
	}
	b.WriteString("| Category | Entries | Files |\n|---|---:|---|\n")
	for _, r := range rows {
		fmt.Fprintf(&b, "| %s | %d | [.srs](%s.srs) · [.json](%s.json) |\n", r.cat, r.count, r.cat, r.cat)
	}
	return os.WriteFile(filepath.Join(outDir, "README.md"), []byte(b.String()), 0o644)
}

func build(ctx context.Context, src config.Source, opt options, resolver *asn.Resolver) (int, error) {
	merged := &model.RuleSet{}
	skipped := map[string]int{}
	var detected string

	for _, url := range src.URLs {
		data, err := source.Fetch(ctx, url)
		if err != nil {
			return 0, fmt.Errorf("fetch %s: %w", url, err)
		}
		format := src.Format
		if format == "" || format == "auto" {
			format = parser.Detect(data, url)
			detected = format
		}
		p, err := parser.Get(format)
		if err != nil {
			return 0, err
		}
		res, err := p.Parse(data)
		if err != nil {
			return 0, fmt.Errorf("parse %s: %w", url, err)
		}
		merged.Merge(res.RuleSet)
		for k, v := range res.Skipped {
			skipped[k] += v
		}
	}

	expandASN(ctx, merged, resolver, skipped)

	ov, err := override.Load(opt.overridesDir, src.Category)
	if err != nil {
		return 0, fmt.Errorf("load override: %w", err)
	}
	if ov != nil {
		ov.Apply(merged)
	}

	var st transform.Stats
	if opt.optimize {
		st = transform.Process(merged)
	} else {
		merged.Normalize()
	}

	minVer := merged.MinVersion()
	jsonBytes, err := compile.JSON(merged, minVer)
	if err != nil {
		return 0, fmt.Errorf("render json: %w", err)
	}
	jsonPath := filepath.Join(opt.outDir, src.Category+".json")
	if err := os.WriteFile(jsonPath, append(jsonBytes, '\n'), 0o644); err != nil {
		return 0, err
	}

	versions, below := parseVersions(opt.srsVersions, minVer)
	for idx, v := range versions {
		srsPath := filepath.Join(opt.outDir, src.Category+".srs")
		if idx > 0 {
			srsPath = filepath.Join(opt.outDir, fmt.Sprintf("%s.v%d.srs", src.Category, v))
		}
		if err := compile.SRS(jsonBytes, srsPath, v); err != nil {
			return 0, fmt.Errorf("compile srs v%d: %w", v, err)
		}
	}

	logResult(src.Category, merged.Count(), detected, ov != nil, st, skipped, versions, below)
	return merged.Count(), nil
}

// expandASN resolves collected IP-ASN values to CIDRs (appending to IPCIDR)
// when a resolver is configured, then clears them. Without a resolver, or for
// ASNs that fail to resolve, the count is recorded in skipped so the drop is
// never silent. Resolution does not fail the category.
func expandASN(ctx context.Context, rs *model.RuleSet, resolver *asn.Resolver, skipped map[string]int) {
	if len(rs.ASN) == 0 {
		return
	}
	uniq := map[string]bool{}
	for _, a := range rs.ASN {
		uniq[a] = true
	}
	if resolver == nil {
		skipped["IP-ASN"] += len(uniq)
		rs.ASN = nil
		return
	}
	for a := range uniq {
		cidrs, err := resolver.Resolve(ctx, a)
		if err != nil {
			skipped["IP-ASN(unresolved)"]++
			continue
		}
		rs.IPCIDR = append(rs.IPCIDR, cidrs...)
	}
	rs.ASN = nil
}

// parseVersions resolves the -srs-versions flag against the minimum version the
// content requires. "auto"/"" -> [min]. Requested versions below min are
// reported (returned in below) and skipped.
func parseVersions(spec string, min uint8) (use, below []uint8) {
	spec = strings.TrimSpace(spec)
	if spec == "" || spec == "auto" {
		return []uint8{min}, nil
	}
	seen := map[uint8]bool{}
	for _, part := range strings.Split(spec, ",") {
		part = strings.TrimSpace(part)
		if part == "" {
			continue
		}
		n, err := strconv.Atoi(part)
		if err != nil || n < 1 || n > 255 {
			continue
		}
		v := uint8(n)
		if v < min {
			below = append(below, v)
			continue
		}
		if !seen[v] {
			seen[v] = true
			use = append(use, v)
		}
	}
	if len(use) == 0 {
		use = []uint8{min}
	}
	sort.Slice(use, func(i, j int) bool { return use[i] < use[j] })
	return use, below
}

func logResult(category string, count int, detected string, overridden bool, st transform.Stats, skipped map[string]int, versions, below []uint8) {
	note := ""
	if detected != "" {
		note += " (auto:" + detected + ")"
	}
	if overridden {
		note += " (override)"
	}
	if len(versions) > 1 {
		note += fmt.Sprintf(" (srs v%v)", versions)
	}
	if count == 0 {
		log.Printf("[WARN] %-12s produced 0 entries%s", category, note)
	} else {
		log.Printf("[ OK ] %-12s %6d entries%s", category, count, note)
	}
	if st.Changed() {
		log.Printf("        %-12s optimized: -kw %d, -suffix %d, cidr %d->%d, -regex %d",
			category, st.KeywordCollapsed, st.SuffixCollapsed, st.CIDRBefore, st.CIDRAfter, st.RegexDropped)
	}
	if len(below) > 0 {
		log.Printf("        %-12s skipped srs versions below min: %v", category, below)
	}
	if len(skipped) > 0 {
		log.Printf("        %-12s skipped %v", category, sortedSkip(skipped))
	}
}

func sortedSkip(m map[string]int) []string {
	out := make([]string, 0, len(m))
	for k, v := range m {
		out = append(out, fmt.Sprintf("%s x%d", k, v))
	}
	sort.Strings(out)
	return out
}
